server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: messaging-microservice-foodcourt

jwt:
  secret: ${JWT_SECRET_KEY}
  validity: 3600000

twilio:
  accountSid: ${ACCOUNT_SID}
  authToken: ${AUTH_TOKEN}
  fromPhone: ${FROM_PHONE}
